version: '3.5'
services:
  backend:
    container_name: realtime-chat-be
    image: nmluci/realtime-chat-be
    build:
      context: .
      args:
        BUILD_ENV: prod
    restart: unless-stopped
    volumes:
      - ./conf:/app/conf
      - ./migrations:/app/migrations
      - server_data:/appdata
    ports:
      - "8080:8080"
volumes:
  server_data: {}